name: Preview

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

concurrency:
  group: pages-preview-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.preview.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
      - id: preview
        uses: actions/preview-pages@v1
